#!/usr/bin/env python
#
# Convert any audio files into CDDA quality FLAC tracks.
#
# Copyright © 2015 Mark Karpov <markkarpov@openmailbox.org>
#
# flacize is free software: you can redistribute it and/or modify it under
# the terms of the GNU General Public License as published by the Free
# Software Foundation, either version 3 of the License, or (at your option)
# any later version.
#
# flacize is distributed in the hope that it will be useful, but WITHOUT ANY
# WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
# FOR A PARTICULAR PURPOSE. See the GNU General Public License for more
# details.
#
# You should have received a copy of the GNU General Public License along
# with this program. If not, see <http://www.gnu.org/licenses/>.

import argparse
import os
import sys

# Constants and other useful values

prog_name = os.path.basename(__file__)
version = '0.1.0'
description = 'Convert any audio files into CDDA quality FLAC tracks'
license = """
flacize — Convert any audio files into CDDA quality FLAC tracks

Copyright © 2015 Mark Karpov

flacize is free software: you can redistribute it and/or modify it under the
terms of the GNU General Public License as published by the Free Software
Foundation, either version 3 of the License, or (at your option) any later
version.

flacize is distributed in the hope that it will be useful, but WITHOUT ANY
WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
FOR A PARTICULAR PURPOSE. See the GNU General Public License for more
details.

You should have received a copy of the GNU General Public License along
with this program. If not, see <http://www.gnu.org/licenses/>.
"""

parser = argparse.ArgumentParser(description=description)

# TODO: write more stuff, so it does something useful…
