#!/usr/bin/env python
#
# Convert any audio files into CDDA quality FLAC tracks.
#
# Copyright © 2015 Mark Karpov <markkarpov@openmailbox.org>
#
# flacize is free software: you can redistribute it and/or modify it under
# the terms of the GNU General Public License as published by the Free
# Software Foundation, either version 3 of the License, or (at your option)
# any later version.
#
# flacize is distributed in the hope that it will be useful, but WITHOUT ANY
# WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
# FOR A PARTICULAR PURPOSE. See the GNU General Public License for more
# details.
#
# You should have received a copy of the GNU General Public License along
# with this program. If not, see <http://www.gnu.org/licenses/>.

from decimal import Decimal
import argparse
import copy
import fnmatch
import itertools
import os
import re
import shutil
import subprocess
import sys
import taglib

# Constants and other useful values

prog_name = os.path.basename(__file__)
version = '0.1.0'
description = 'Convert any audio files into CDDA quality FLAC tracks'
license = """flacize — Convert any audio files into CDDA quality FLAC tracks

Copyright © 2015 Mark Karpov

flacize is free software: you can redistribute it and/or modify it under the
terms of the GNU General Public License as published by the Free Software
Foundation, either version 3 of the License, or (at your option) any later
version.

flacize is distributed in the hope that it will be useful, but WITHOUT ANY
WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
FOR A PARTICULAR PURPOSE. See the GNU General Public License for more
details.

You should have received a copy of the GNU General Public License along
with this program. If not, see <http://www.gnu.org/licenses/>.
"""

aexts = frozenset( # recognized audio formats and corresponding extensions:
    { 'aac'    # Advanced Audio Coding
    , 'aif'    # Audio Interchange File Format
    , 'aifc'   # Audio Interchange File Format
    , 'aiff'   # Audio Interchange File Format
    , 'ape'    # Monkey's Audio
    , 'flac'   # Free Lossless Audio Codec
    , 'm4a'    # Advanced Audio Coding
    , 'm4p'    # Advanced Audio Coding
    , 'mp4'    # Advanced Audio Coding
    , 'wav'    # Microsoft Wave
    , 'wma'    # Windows Media Audio 9 Lossless
    , 'wv' })  # WavPack

parser = argparse.ArgumentParser(description=description)
parser.add_argument('dir', metavar='DIR', nargs='?', default=os.getcwd(),
                    help='directory to scan')
parser.add_argument('-o', '--output', metavar='DIR', dest='out_dir', default='',
                    help='output directory (created if needed)')
parser.add_argument('-r', '--rate', metavar='N', dest='rate', default=44100,
                    type=int,
                    help='output sample rate (defaults to 44100 Hz)')
parser.add_argument('-w', '--width', metavar='N', dest='width', default=16,
                    type=int,
                    help='output sample width (defaults to 16 bit)')
parser.add_argument('-c', '--channels', metavar='N', dest='chs', default=2,
                    type=int,
                    help='number of channels (defaults to 2)')
parser.add_argument('-p', '--preserve', action='store_true', dest='preserve',
                    help='preserve quality of originals')
parser.add_argument('-d', '--delete', action='store_true', dest='delete',
                    help='delete original files after conversion')
parser.add_argument('-s', '--shift', metavar='N', dest='shift', default=0,
                    type=int,
                    help='add N to index of every track')
parser.add_argument('-t', '--total', metavar='N', dest='total',
                    type=int,
                    help='specify total number of tracks N')
parser.add_argument('-e', '--crop', metavar='N', dest='crop', default=0,
                    type=int,
                    help='crop last N tracks (e.g. remove bonus tracks)')
parser.add_argument('-a', '--dont-ask', action='store_true', dest='dont_ask',
                    help="don't ask user even if cannot deduce some tag")
parser.add_argument('--license', action='store_true', dest='show_license',
                    help="show program's license and exit")
parser.add_argument('--version', action='version',
                    version='%(prog)s ' + version)

args = parser.parse_args()
deletable = set()

# Some functions that help us to fulfill our task.

def failure(str):
    """
    Print error message ‘str’ to stderr and exit with code 1.
    """
    print(prog_name, ": error: ", str, file=sys.stderr)
    exit(1)

def tag_fallback(tag_name, deduced_val='?') -> str:
    """
    Ask user to enter value of tag ‘tag_name’ manually (last resort). Return
    user's input or value of ‘deduced_val’ is ‘args.dont_ask’ is
    ‘True’. Remember return value and use it if the same tag is asked
    again. This function is best for “ALBUM”, “ARTIST”, and “DATE” tags.
    """
    if not tag_name in tag_fallback.vals:
        tag_fallback.vals[tag_name] = (deduced_val if args.dont_ask else
    input('Cannot deduce value of tag ‘%s’ ≈ “%s”: ' % (tag_name, deduced_val))
        or deduced_val)
    return tag_fallback.vals[tag_name]

tag_fallback.vals = {} # here we store already asked tags

def extract_title(s) -> str:
    """
    Return sub-string of ‘s’ from first alphabetic char to end.
    """
    return s[next((i for i, v in enumerate(s) if v.isalpha())):]

def extract_num_prefix(s) -> str:
    """
    Return sub-string of ‘s’ containing its (possibly empty) numeric prefix.
    """
    return ''.join(itertools.takewhile(str.isdecimal, s.strip()))

def simplify_tag(s) -> str:
    """
    Simplify tag deleting trailing white space, extra white space between
    words, and everything in brackets []. Also, trim leading zeros.
    """
    return ' '.join(re.sub(r'\[.*\]|\{.*\}', '', s).split()).lstrip('0')

def output_name(out_dir, name, ext) -> str:
    """
    Join directory ‘out_dir’, base name ‘name’ and extension ‘ext’. ‘name’
    is transformed so it can be used on all major operating systems.
    """
    return os.path.join(out_dir, re.sub('[\x00/\\\\?%*:|"<>#]', '_', name) +
                        (os.path.extsep + ext if ext else ''))

def protected_name(filename) -> str:
    """
    Return protected version of ‘filename’. It's usually used to avoid
    overreads when original file name coincides with result file name.
    """
    head, tail = os.path.split(filename)
    return os.path.join(head, '__' + tail)

def parse_time(time_str) -> Decimal:
    """
    Parse ‘time_str’ according to the pattern: <min>:<sec>:<millis>. Return
    number of seconds (float) or None on failure.
    """
    t = re.match(r'^(\d\d):(\d\d):(\d\d)$', time_str)
    if t:
        min, sec, millis = t.groups()
        return (Decimal(min) * 60 + Decimal(sec) +
                Decimal(millis) * Decimal('0.01'))
    return None

class Track:
    """
    The class models a track to convert. It includes information about
    location of original file, name of result file, possible changes in
    various parameters of audio and collection of tags.
    """
    def __init__(self, origin, tags={},
                 seek_pos=None, duration=None,
                 raw_index=1, raw_total=1):
        self.origin = origin
        # set quality parameters unless we must preserve it
        if args.preserve:
            self.sample_rate  = None
            self.sample_width = None
            self.channels     = None
        else:
            self.sample_rate  = args.rate
            self.sample_width = args.width
            self.channels     = args.chs
        # start and end time (only useful when splitting a CUE)
        self.seek_pos = seek_pos
        self.duration = duration
        # copy or deduce tags, ‘tags’ variable contains raw extracted data
        self.tags = {}
        pdir  = os.path.basename(os.path.abspath(args.dir))
        bname = os.path.splitext(os.path.basename(origin))[0]
        # ALBUM
        self.tags['ALBUM'] = (tags.get('ALBUM')
            or tag_fallback('ALBUM', extract_title(pdir)))
        # ARTIST
        self.tags['ARTIST'] = (tags.get('ARTIST')
            or tag_fallback('ARTIST'))
        # DATE
        self.tags['DATE'] = (tags.get('DATE')
            or tag_fallback('DATE', extract_num_prefix(pdir)))
        # TITLE
        self.tags['TITLE'] = (tags.get('TITLE')
            or extract_title(bname))
        # TRACKNUMBER & TRACKTOTAL
        tnum, *atot = (tags.get('TRACKNUMBER')
            or extract_num_prefix(bname)).split('/')
        tnum = (int(tnum) if tnum.isdigit() else raw_index) + args.shift
        if args.total:
            ttot = args.total
        else:
            ttot = tags.get('TRACKTOTAL', atot and atot[0])
            ttot = int(ttot) if ttot else raw_total
            if args.crop:
                ttot -= args.crop
        self.tags['TRACKNUMBER'] = str(tnum)
        self.tags['TRACKTOTAL'] = str(ttot)
        # simplify tag values after all…
        self.tags = {tag: simplify_tag(self.tags[tag]) for tag in self.tags}
        # get output file name
        if tnum > ttot:
            self.result = None
        else:
            self.result = output_name(args.out_dir,
                ('%02d' % tnum) + ' ' + self.tags['TITLE'], 'flac')

    def convert_file(self) -> str:
        """
        Convert the audio file using FFmpeg converter.
        """
        # avoid overreads
        if (self.result and
            os.path.abspath(self.origin) == os.path.abspath(self.result)):
            protected = protected_name(self.origin)
            os.rename(self.origin, protected)
            self.origin = protected
        deletable.add(self.origin)
        if not self.result: return
        # construct arguments for invocation of ‘ffmpeg’
        cmd = ['ffmpeg', '-y']
        def add_to_cmd(value, option):
            nonlocal cmd
            if value:
                cmd.extend([option, str(value)])
        add_to_cmd(self.seek_pos, '-ss')
        cmd.extend(['-i', self.origin,
                    '-acodec', 'flac',
                    '-compression_level', '8'])
        add_to_cmd(self.duration, '-to')
        add_to_cmd(self.sample_rate, '-ar')
        add_to_cmd({8: 'u8', 16: 's16', 32: 's32'}.get(self.sample_width),
                   '-sample_fmt')
        add_to_cmd(self.channels, '-ac')
        cmd.append(self.result)
        subprocess.check_call(cmd)
        # overwrite tags
        F = taglib.File(self.result)
        F.tags = {k: [self.tags[k]] for k in self.tags}
        F.save()
        # finalize
        self.result

def get_tracks() -> list:
    """
    Return list of dictionaries containing full description of every track
    to process. The returned information is already corrected according to
    used command line options. Directory to scan is ‘arg.dir’, dispatch for
    .cue + audio data is automatic.
    """
    all_files = [os.path.join(args.dir, f) for f in os.listdir(args.dir)]
    cue_files = fnmatch.filter(all_files, '*.cue')
    if len(cue_files) > 1:
        failure('too many .cue files in ‘%s’' % os.path.abspath(arg.dir))
    if len(cue_files) == 1:
        return get_cue_tracks(cue_files[0])
    else:
        return get_dis_tracks([f for f in sorted(all_files)
                               if os.path.splitext(f)[1][1:] in aexts])

def get_cue_tracks(cue_file) -> list:
    """
    Return list of ‘Track’ objects — descriptions of every track to
    process. This function tries to process .cue + audio thing.
    """
    deletable.add(cue_file)
    params = []
    index = None
    cmn_params = {'tags': {}}
    for line in open(cue_file):
        def check_cmn(regexp, param_name, tag=False) -> bool:
            t = re.match(regexp, line)
            if t:
                t = t.group(1).strip('"')
                if tag:
                    cmn_params['tags'][param_name] = t
                else:
                    cmn_params[param_name] = t
                return True
            return False
        def check_id(regexp, param_name, tag=False) -> bool:
            t = re.match(regexp, line)
            if t:
                t = t.group(1).strip('"')
                if tag:
                    params[index - 1]['tags'][param_name] = t
                else:
                    params[index - 1][param_name] = t
                return True
            return False
        # parameters that are common among several tracks
        if check_cmn(r'^\s*FILE\s+(".*"|\S+)\s*', 'origin'):
            continue
        if not index:
            if check_cmn(r'^\s*TITLE\s+(".*"|\S+)\s*', 'ALBUM', tag=True):
                continue
            if check_cmn(r'^\s*PERFORMER\s+(".*"|\S+)\s*', 'ARTIST', tag=True):
                continue
            if check_cmn(r'^\s*REM\s+DATE\s+("?\d+"?)\s*', 'DATE', tag=True):
                continue
        # individual track parsing
        t = re.match(r'^\s*TRACK\s+(\d+)\s+AUDIO', line)
        if t: # new track
            index = int(t.group(1))
            params.append(copy.deepcopy(cmn_params))
            params[index - 1]['tags']['TRACKNUMBER'] = str(index)
            params[index - 1]['raw_index'] = index
        elif index: # continuing description of a track…
            if check_id(r'^\s*TITLE\s+(".*"|\S+)\s*', 'TITLE', tag=True):
                continue
            if check_id(r'^\s*INDEX\s+01\s+([\d|:]+)\s*', 'seek_pos'):
                time_str = params[index - 1]['seek_pos']
                time_sec = parse_time(time_str)
                params[index-1]['seek_pos'] = time_sec
                # now we can write ‘duration’ parameter of previous track
                if index > 1:
                    seek_pos = params[index - 2]['seek_pos']
                    params[index - 2]['duration'] = time_sec - seek_pos
                continue
    # add “TRACKTOTAL” tag
    track_total = len(params)
    for p in params:
        p['tags']['TRACKTOTAL'] = track_total
        p['raw_total'] = track_total
    # apply params to ‘Track’ and return created objects
    return [Track(**p) for p in params]

def get_dis_tracks(files) -> list:
    """
    Return list of ‘Track’ objects — descriptions of every track to
    process. This function works with collection of separate tracks.
    """
    total = len(files)
    tracks = []
    for (i, f) in enumerate(files, 1):
        F = taglib.File(f)
        tags = {k: F.tags[k][0] for k in F.tags}
        tracks.append(Track(f, tags=tags, raw_index=i, raw_total=total))
    return tracks

# Execution starts here, show license if user wants to see it.

if args.show_license:
    print(license)
    exit(0)

# Test if FFmpeg console application is present on this system, just in
# case.

if not shutil.which('ffmpeg'):
    failure('cannot find ‘ffmpeg’ program')

# If user has specified output directory, we should make sure that it does
# exist.

if args.out_dir: os.makedirs(args.out_dir, exist_ok=True)

# First of all, we need to get list of dictionaries that contain meta-data,
# file name, information about start time and end time, indexation and total
# number of tracks, etc. The whole list must be formed before translation
# because need to have all the data at once (for example to count total
# number of tracks or specify start and end time for audio that comes with a
# .cue file). Every dictionary in the list may duplicate some info, the idea
# is that it must contain full description of given track for processing.

tracks = get_tracks()

for track in tracks:
    track.convert_file()

if args.delete:
    for f in deletable:
        os.remove(f)
